stages:
  - build
  - test
  - deploy

build the package:
  stage: build
  script:
    - npm install
  tags:
    - npm
  except:
    - tags

execute npm tests:
  stage: test
  script:
    - npm run-script test-and-cover
  tags:
    - npm
  except:
    - tags

publish coveralls:
  stage: deploy
  script:
    - COVERALLS_SERVICE_NAME="GitLab CI" npm run-script publish-coveralls
  tags:
      - npm
  except:
    - tags
